openapi: 3.1.0
info:
  title: Student Management System
  version: 1.0.0
servers:
- url: https://localhost:8081/api
paths:
  /students:
    get:
      operationId: getAllStudents
      parameters:
      - description: Page number (1-based).
        explode: true
        in: query
        name: page
        required: false
        schema:
          default: 1
          minimum: 1
          type: integer
        style: form
      - description: Number of items per page.
        explode: true
        in: query
        name: size
        required: false
        schema:
          default: 10
          maximum: 100
          minimum: 1
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetAllStudentsResponse"
          description: Get all students successfully
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalServerError"
      summary: Get all students
      x-accepts:
      - application/json
    post:
      operationId: addNewStudent
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Student"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AddNewStudentResponse"
          description: Add new student successfully
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalServerError"
      summary: Add a new student
      x-content-type: application/json
      x-accepts:
      - application/json
  /students/{id}:
    delete:
      operationId: deleteStudentById
      parameters:
      - description: Student Id
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeleteStudentResponse"
          description: Delete student information successfully
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalServerError"
      summary: Delete a student by Id
      x-accepts:
      - application/json
    get:
      operationId: getStudentById
      parameters:
      - description: Student Id
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetStudentByIdResponse"
          description: Get student information successfully
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalServerError"
      summary: Get a student by Id
      x-accepts:
      - application/json
    parameters:
    - description: Student Id
      explode: false
      in: path
      name: id
      required: true
      schema:
        type: string
      style: simple
    put:
      operationId: updateStudent
      parameters:
      - description: Student Id
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Student"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdateStudentResponse"
          description: Update student information successfully
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalServerError"
      summary: Update a student
      x-content-type: application/json
      x-accepts:
      - application/json
components:
  responses:
    BadRequest:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/inline_object"
      description: Bad Request
    InternalServerError:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/inline_object"
      description: Internal Server Error
  schemas:
    Student:
      example:
        id: 1
        code: 1234
        name: Khanh
      properties:
        id:
          example: 1
          format: int64
          type: integer
        code:
          example: 1234
          type: string
        name:
          example: Khanh
          type: string
    GetAllStudentsResponse:
      allOf:
      - properties:
          success:
            type: boolean
          message:
            type: string
        required:
        - success
      - properties:
          page:
            description: Page number
            example: 1
            type: integer
          size:
            description: Number of items
            example: 10
            type: integer
          totalItems:
            description: Total items
            example: 99
            type: integer
          totalPages:
            description: Total pages
            example: 10
            type: integer
          data:
            items:
              $ref: "#/components/schemas/Student"
            type: array
            default: null
        type: object
        example: null
      example:
        success: true
        message: message
        page: 1
        size: 10
        totalItems: 99
        totalPages: 10
        data:
        - id: 1
          code: 1234
          name: Khanh
        - id: 1
          code: 1234
          name: Khanh
    GetStudentByIdResponse:
      allOf:
      - properties:
          success:
            type: boolean
          message:
            type: string
        required:
        - success
      - properties:
          data:
            $ref: "#/components/schemas/Student"
        type: object
        example: null
      example:
        success: true
        message: message
        data:
          id: 1
          code: 1234
          name: Khanh
    AddNewStudentResponse:
      allOf:
      - properties:
          success:
            type: boolean
          message:
            type: string
        required:
        - success
      - properties:
          data:
            $ref: "#/components/schemas/Student"
        type: object
        example: null
      example:
        success: true
        message: message
        data:
          id: 1
          code: 1234
          name: Khanh
    UpdateStudentResponse:
      allOf:
      - properties:
          success:
            type: boolean
          message:
            type: string
        required:
        - success
      - properties:
          data:
            $ref: "#/components/schemas/Student"
        type: object
        example: null
      example:
        success: true
        message: message
        data:
          id: 1
          code: 1234
          name: Khanh
    DeleteStudentResponse:
      allOf:
      - properties:
          success:
            type: boolean
          message:
            type: string
        required:
        - success
      example:
        success: true
        message: Student deleted!
    inline_object:
      allOf:
      - properties:
          success:
            type: boolean
          message:
            type: string
        required:
        - success
      example:
        success: false
        message: Required fields are missing
